# apiVersion: v1
# name: backend
# version: 0.0.1
# description: this is the helm implementation of backend in expense project

apiVersion: v2
name: backend
description: Expense Backend
type: application
version: 0.1.0
appVersion: "1.0.0"